/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package appController;

import java.io.IOException;

import data.MyDataSet;
import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;

//#110101
public class App extends Application {

	private AppController controller;

	@Override
	public void start(Stage primaryStage) {
//		// TODO Auto-generated method stub
//		FXMLLoader lod = new FXMLLoader(getClass().getResource("BasicAppView.fxml"));
//		BasicAppViewController appviewController = lod.getController();
		MyDataSet model = new MyDataSet();
		controller = new AppController(model);

		// FXMLLoader basiclod = new
		// FXMLLoader(getClass().getResource("BasicAppView.fxml"));
		// Parent r = basiclod.load();

		// BasicAppViewController basicController = basiclod.getController();

		// basicController.setModelListener(model);
		// basicController.setAppController(controller);

		FXMLLoader lod = new FXMLLoader(getClass().getResource("StartView.fxml"));

		// FXMLLoader lod = new
		// FXMLLoader(Launcher.class.getResource("AddFriendView.fxml"));

		Parent root = new HBox();// empty page
		try {
			root = lod.load();
		} catch (IOException e) {
			System.out.println("\n\\n\n\n error by loading the fxml file\n\n\n");
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		AnmeldungController anmeldenController = lod.getController();

		anmeldenController.setAppController(controller);
		anmeldenController.setModelListener(model);

		Scene scene = new Scene(root);

		primaryStage.setTitle("abdoo chat app");
		primaryStage.setScene(scene);
		primaryStage.setMinHeight(550);
		primaryStage.setMinWidth(600);

		primaryStage.setOnCloseRequest(new EventHandler<WindowEvent>() {

			@Override
			public void handle(WindowEvent event) {

				// TODO Auto-generated method stub

				controller.shutDownSchedular();

			}
		});

		primaryStage.show();

	}

	public static void main(String[] args) {
		launch(args);
	}

}
