/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package appController;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Modality;
import javafx.stage.Stage;

public class App2_forTesting extends Application {

//	@Override
//	public void start(Stage primaryStage) throws Exception {
//		// TODO Auto-generated method stub
//
//		VBox root = new VBox();
//
//		Button add = new Button("");
//
//		/*
//		 * BackgroundImage backgroundImage = new BackgroundImage( new
//		 * Image(getClass().getResource("mail_senden.png").toExternalForm()),
//		 * BackgroundRepeat.NO_REPEAT, BackgroundRepeat.NO_REPEAT,
//		 * BackgroundPosition.DEFAULT, BackgroundSize.DEFAULT);
//		 */
//		add.setMaxHeight(30);
//		add.setMaxWidth(30);
//		Image paperClipImage = new Image(getClass().getResourceAsStream("paper_clip.png"));
//		add.setGraphic(new ImageView(paperClipImage));
//
//		// Background background = new Background(backgroundImage);
//
//		// add.setBackground(background);
////		add.setStyle("-fx-background-image: url('mail_senden.png')");
//
//		root.getChildren().add(add);
//		Scene scene = new Scene(root);
//
//		primaryStage.setTitle("abdoo chat app");
//		primaryStage.setScene(scene);
//		primaryStage.setMinHeight(550);
//		primaryStage.setMinWidth(600);
//		primaryStage.show();
//
//	}

	@Override
	public void start(final Stage primaryStage) {
		Button btn = new Button();
		btn.setText("Open Dialog");
		btn.setOnAction(new EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
				final Stage dialog = new Stage();
//				dialog.initModality(Modality.NONE);
				dialog.initModality(Modality.APPLICATION_MODAL);
				dialog.initOwner(primaryStage);
				VBox dialogVbox = new VBox(20);
				dialogVbox.getChildren().add(new Text("This is a Dialog"));
				Scene dialogScene = new Scene(dialogVbox, 300, 200);
				dialog.setScene(dialogScene);
				dialog.show();
			}
		});

		VBox root = new VBox();
		root.getChildren().add(btn);
		Scene scene = new Scene(root);

		primaryStage.setTitle("abdoo chat app");
		primaryStage.setScene(scene);
		primaryStage.setMinHeight(550);
		primaryStage.setMinWidth(600);
		primaryStage.show();

	}

//	dialog.initModality(Modality.NONE);

	public static void main(String[] args) {
		launch(args);
	}

}
